### ISSUE TITLE
Ability to set backend state without token in emulation mode

### ISSUE THREAD

**Issue by lolmaus** [bread-maker/bread-maker-onion2#13]
In the beginning of a test, I should be able to request the backend to assume a certain state. This should be possible without a password or token.

I can see two ways of achieving this:

* Via a special API endpoint that lets me load a JSON config describing any aspects of state.
* By adding a special param that will remove password/token requirement from all API endpoints.

Of course, the special endpoint/param should be disabled in non-emulation mode.

The first way is much better from the frontend perspective: it would allow setting all aspects of state with a single request.

**Comment by ClusterM** [comment]
Added "forceauth" argument. It can be used instead of "password" or "token" argements in emulation mode.
