### ISSUE TITLE
Emulation is not working with external web server

### ISSUE THREAD

**Issue by ClusterM** [bread-maker/bread-maker-onion2#14]
Web server running as daemon can't access "EMULATION" variable, so emulation is not working.

**Comment by lolmaus** [comment]
It does work for me when I run it like this:

```
docker-compose build backend
docker-compose up backend
```

**Comment by vitkhab** [comment]
Which web server? Please provide commands you've executed and error log.

**Comment by ClusterM** [comment]
Nevermind.
