### ISSUE TITLE
Server incorrectly treats OPTIONS

### ISSUE THREAD

**Issue by lolmaus** [bread-maker/bread-maker-onion2#18]
When a browser is about to make a non-GET request to a domain different from current URL, it first makes an OPTIONS request to describe the communication options for the target resource, such as CORS.

The frontend app has no control over the OPTIONS request other than the URL. The OPTIONS request does not bear the payload (body).

The backend incorrectly treats the OPTIONS request as an actual API call and responds with 400 or 401.

For more info, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS

**Comment by ClusterM** [comment]
Fixed?

**Comment by lolmaus** [comment]
Yep. :+1:
