### ISSUE TITLE
Stop time in emulation mode

### ISSUE THREAD

**Issue by lolmaus** [bread-maker/bread-maker-onion2#2]
Time should not be running in emulation mode because it makes tests unpredictable.

Whether time should be frozen can be controlled via a command line argument.

**Comment by lolmaus** [comment]
Uhm, I've discovered that the bread maker can enter an error state.

How do tell the emulator to enter a specific error state?

@ClusterM, I need full control of every aspect of backend state.

**Comment by lolmaus** [comment]
My tests are failing randomly because temp is `25.02` all of a sudden, while `25` sharp is asserted.

**Comment by ClusterM** [comment]
> How do tell the emulator to enter a specific error state?

I'll make emulation of error states. Please create separate issue for this.

> My tests are failing randomly because temp is 25.02 all of a sudden, while 25 sharp is asserted.

You can control current temperature. But you can't be sure that temperature is equal to the target. So this test should be failed.

**Comment by lolmaus** [comment]
> you can't be sure that temperature is equal to the target

I'm not comparing `temp` to `target_temp`. I'm comparing `temp` set by emulation API to `temp` reported by stats immediately afterwards.

**Comment by ClusterM** [comment]
Done. Time will run only via emu.time method now. Also this method returns not immediately now.
Please note that start time is current time by defaut.
Added "emu.reset" method. It just restarts emulation. You can pass "time" argument to it to set start time. Default is current time. Please note that emu.reset will note reset current temperature (yet?).
