### ISSUE TITLE
Implement settings API

### ISSUE THREAD

**Issue by lolmaus** [bread-maker/bread-maker-onion2#3]
I need to store these settings:

* locale
* ~~timezone~~
* ~~Celsius/Fahrenheit~~

This could be an arbitrary JSON storage or individual API endpoints. Arbitrary storage is preferable because it will allow me to add more settings without having to update the backend.

**Comment by lolmaus** [comment]
Reading settings should be available to anons. Writing settings -- to authenticated users only.

**Comment by lolmaus** [comment]
I've found timezone API in docs. ^_^

I don't need Celsius/Fahrenheit, I will deduce that from locale: US is Fahrenheit, everything else is Celsius.

**Comment by ClusterM** [comment]
Added config.misc.get and config.misc.set methods.
* config.misc.get returns all values
* config.misc.set requires "key" and "value" arguments

**Comment by lolmaus** [comment]
Nice!

**Comment by lolmaus** [comment]
Please document it. :bow:

**Comment by ClusterM** [comment]
Sorry, forgot about it. Documented!
