### ISSUE TITLE
Quitting `breadmaker.sh` with Ctrl+C does not actually quit

### ISSUE THREAD

**Issue by lolmaus** [bread-maker/bread-maker-onion2#5]
When I run `root/usr/share/breadmaker/breadmaker.sh` and then hit `Ctrl+C`, nothing happens. The log is still running, I have to use task manager to kill the script in order to return to the terminal.

Hitting `Ctrl+C` more than once produces this:

> ./breadmaker.sh: line 1: kill: (22884) - No such process

...and then logging continues.

**Comment by ClusterM** [comment]
Seems like spawned php script still running. Can you compare PID in this message with real PID of emulator process?

**Comment by lolmaus** [comment]
The PIDs are different.

**Comment by lolmaus** [comment]
Looks like it successfully kills a child process but does not kill itself.

**Comment by ClusterM** [comment]
Please test it now. Seems like it depends on shell. Omega 2 uses busybox/sh.

**Comment by lolmaus** [comment]
Please reference issue id in commit message.

Which branch should I try?

**Comment by lolmaus** [comment]
On master it exits correctly now, but there's a different problem. Reporting in another issue.
