### ISSUE TITLE
Erroneous HTTP responses should respond with an error code (4xx)

### ISSUE THREAD

**Issue by lolmaus** [bread-maker/bread-maker-onion2#8]

**Comment by ClusterM** [comment]
How about 5xx for internal errors?

**Comment by lolmaus** [comment]
Indeed *internal* errors should yield 5xx.

But failing to provide a required argument is not an internal error, it's users fault. Thus, such errors should yield 4xx.

**Comment by ClusterM** [comment]
Done. Error codes are declared into api/consts.php

**Comment by lolmaus** [comment]
:+1:
